t5_1e-3_50_wmt_en_ro_baseline_wmt_en_ro
check duplicate
Traceback (most recent call last):
  File "/home/nlplab/hdd1/gyop/UnitInit/test_generation.py", line 69, in <module>
    dataset = load_dataset("wmt16", "ro-en" , cache_dir=server_env.data_path)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/datasets/load.py", line 1797, in dataset_module_factory
    dataset_info = hf_api.dataset_info(
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 2282, in dataset_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/nlplab/hdd1/gyop/UnitInit/test_generation.py", line 1, in <module>
    from datasets import load_dataset, load_metric
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/datasets/__init__.py", line 18, in <module>
    from .arrow_dataset import Dataset
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 58, in <module>
    import numpy as np
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/numpy/core/__init__.py", line 88, in <module>
    from . import getlimits
  File "/home/nlplab/anaconda3/envs/UnitInit/lib/python3.9/site-packages/numpy/core/getlimits.py", line 379, in <module>
    class finfo:
KeyboardInterrupt
